import { MetaData, Workflow } from '../models/wf.model';

export const DATA: any = {
  Workflow: {
    Name: 'WFApp1',
    WFID: 'bgE6hpSnpBZTu@tVOEGgDA==',
    Ver: '3.0',
    FriendlyName: 'WFApp1',
    TypeID: '8595',
    Status: '1',
    WorkflowMode: 'Edit',
    ProcessName: 'AtsApp1',
    StageList: ['stg1app1', 'stg2app1', 'stagemid'],
    Stages: {
      stg1app1: {
        Name: 'Stg1_app1',
        FriendlyName: 'Stg1_app1',
        Guid: 'stg1app1',
        Status: '1',
        WorkFlowId: 'bgE6hpSnpBZTu@tVOEGgDA==',
        WfoId: 'FwuzZnDCpNK4dTcp9ObTHA==',
        States: {
          St2app1: {
            Name: 'St2_app1',
            FriendlyName: 'St2_app1',
            Status: '1',
            Guid: 'St2app1',
            SpecID: '0',
            SpecificationName: '',
            WfosId: 'XRhrR58QlT94sx@aX6TMWw==',
            WfoId: 'FwuzZnDCpNK4dTcp9ObTHA==',
            StateType: '',
            StateRoles: {},
            Triggers: {
              trg2app1: {
                Name: 'Trg2_app1',
                FriendlyName: 'Trg2_app1',
                Type: 'Action',
                ActionName: 'Submit',
                StartStageGUID: 'stg1app1',
                StartStateGUID: 'St2app1',
                StartStageName: 'Stg1_app1',
                StartStateName: 'St2_app1',
                Status: '1',
                WfosId: 'XRhrR58QlT94sx@aX6TMWw==',
                TriggerId: 'iWpiw2@$$$rWXRou0ssB4qzw==',
                TypeID: '2',
                Guid: 'trg2app1',
                ActionRoles: {},
                NotifyRoles: {},
                NotifyCcRoles: {},
                TrgConditions: {
                  '53riHlNhyrQpOiMPSFZYYA==': {
                    EndStageGuid: 'stg1app1',
                    EndStateGuid: 'St3app1',
                    ConditionId: '53riHlNhyrQpOiMPSFZYYA==',
                    Name: 'Trg2_app1_Cond',
                    Description: 'Trg2_app1_Cond',
                    NotifyMsg: '',
                    NotifySubject: '',
                    TriggerId: 'iWpiw2@$$$rWXRou0ssB4qzw==',
                    CondNotifyRole: {},
                    CondFilter: {},
                    CondNotifyCcRole: {},
                  },
                },
              },
              trigger1end: {
                Name: 'TRigger_1End',
                FriendlyName: 'TRigger Name',
                Type: 'Action',
                ActionName: 'Submit',
                StartStageGUID: 'stg1app1',
                StartStateGUID: 'St2app1',
                StartStageName: 'Stg1_app1',
                StartStateName: 'St2_app1',
                Status: '1',
                WfosId: 'XRhrR58QlT94sx@aX6TMWw==',
                TriggerId: 'Z6qAipYdRLFIMeBMKazOiA==',
                TypeID: '2',
                Guid: 'trigger1end',
                ActionRoles: {},
                NotifyRoles: {},
                NotifyCcRoles: {},
                TrgConditions: {
                  'YEkiNrX1jQ6eO0dij4BfAA==': {
                    EndStageGuid: 'stg2app1',
                    EndStateGuid: 'St5app1',
                    ConditionId: 'YEkiNrX1jQ6eO0dij4BfAA==',
                    Name: 'TRigger_1End_Cond',
                    Description: 'TRigger Name_Cond',
                    NotifyMsg: '',
                    NotifySubject: '',
                    TriggerId: 'Z6qAipYdRLFIMeBMKazOiA==',
                    CondNotifyRole: {},
                    CondFilter: {},
                    CondNotifyCcRole: {},
                  },
                },
              },
            },
            CheckList: {},
            Conditions: {},
          },
          St3app1: {
            Name: 'St3_app1',
            FriendlyName: 'St3_app1',
            Status: '1',
            Guid: 'St3app1',
            SpecID: '0',
            SpecificationName: '',
            WfosId: 'm5mnBxyG9jNbd9msv3Z3WA==',
            WfoId: 'FwuzZnDCpNK4dTcp9ObTHA==',
            StateType: '',
            StateRoles: {},
            Triggers: {
              trg3app1: {
                Name: 'Trg3_app1',
                FriendlyName: 'Trg3_app1',
                Type: 'Action',
                ActionName: 'Submit',
                StartStageGUID: 'stg1app1',
                StartStateGUID: 'St3app1',
                StartStageName: 'Stg1_app1',
                StartStateName: 'St3_app1',
                Status: '1',
                WfosId: 'm5mnBxyG9jNbd9msv3Z3WA==',
                TriggerId: 'CvC20amad4OLjYtwyHAONQ==',
                TypeID: '2',
                Guid: 'trg3app1',
                ActionRoles: {},
                NotifyRoles: {},
                NotifyCcRoles: {},
                TrgConditions: {
                  'YlZdzglcjNetL@RnOrbfaQ==': {
                    EndStageGuid: 'stg2app1',
                    EndStateGuid: 'St4app1',
                    ConditionId: 'YlZdzglcjNetL@RnOrbfaQ==',
                    Name: 'Trg3_app1_Cond',
                    Description: 'Trg3_app1_Cond',
                    NotifyMsg: '',
                    NotifySubject: '',
                    TriggerId: 'CvC20amad4OLjYtwyHAONQ==',
                    CondNotifyRole: {},
                    CondFilter: {},
                    CondNotifyCcRole: {},
                  },
                },
              },
              firsttomid: {
                Name: 'firsttomid',
                FriendlyName: 'test mid ex',
                Type: 'Action',
                ActionName: 'Clear',
                StartStageGUID: 'stg1app1',
                StartStateGUID: 'St3app1',
                StartStageName: 'Stg1_app1',
                StartStateName: 'St3_app1',
                Status: '1',
                WfosId: 'm5mnBxyG9jNbd9msv3Z3WA==',
                TriggerId: 'gCiVBVzJ2D91upAW6J8N9A==',
                TypeID: '2',
                Guid: 'firsttomid',
                ActionRoles: {},
                NotifyRoles: {},
                NotifyCcRoles: {},
                TrgConditions: {},
              },
            },
            CheckList: {},
            Conditions: {},
          },
          testStar: {
            Name: 'testStar',
            FriendlyName: 'test start state',
            Status: '1',
            Guid: 'testStar',
            SpecID: '1',
            SpecificationName: 'Start State',
            WfosId: 'iNXwPL80wG6sGp8jgygNYQ==',
            WfoId: 'FwuzZnDCpNK4dTcp9ObTHA==',
            StateType: '',
            StateRoles: {},
            Triggers: {},
            CheckList: {},
            Conditions: {},
          },
        },
        Conditions: {},
      },
      stg2app1: {
        Name: 'Stg2_app1',
        FriendlyName: 'Stg2_app1',
        Guid: 'stg2app1',
        Status: '1',
        WorkFlowId: 'bgE6hpSnpBZTu@tVOEGgDA==',
        WfoId: 'ef7gFEHGCifzCWaJCD4Z7A==',
        States: {
          St4app1: {
            Name: 'St4_app1',
            FriendlyName: 'St4_app1',
            Status: '1',
            Guid: 'St4app1',
            SpecID: '0',
            SpecificationName: '',
            WfosId: '$$$m00Dc$$$Kg@Q2rPeuLLaQxg==',
            WfoId: 'ef7gFEHGCifzCWaJCD4Z7A==',
            StateType: '',
            StateRoles: {},
            Triggers: {
              trg4app1: {
                Name: 'Trg4_app1',
                FriendlyName: 'Trg4_app1',
                Type: 'Action',
                ActionName: 'Submit',
                StartStageGUID: 'stg2app1',
                StartStateGUID: 'St4app1',
                StartStageName: 'Stg2_app1',
                StartStateName: 'St4_app1',
                Status: '1',
                WfosId: '$$$m00Dc$$$Kg@Q2rPeuLLaQxg==',
                TriggerId: 'NavUVaw0ZMjPbscpFrJpWQ==',
                TypeID: '2',
                Guid: 'trg4app1',
                ActionRoles: {},
                NotifyRoles: {},
                NotifyCcRoles: {},
                TrgConditions: {
                  'N8PHHIz4Xvaft2TCMyLKoQ==': {
                    EndStageGuid: 'stg2app1',
                    EndStateGuid: 'St5app1',
                    ConditionId: 'N8PHHIz4Xvaft2TCMyLKoQ==',
                    Name: 'Trg4_app1_Cond',
                    Description: 'Trg4_app1_Cond',
                    NotifyMsg: '',
                    NotifySubject: '',
                    TriggerId: 'NavUVaw0ZMjPbscpFrJpWQ==',
                    CondNotifyRole: {},
                    CondFilter: {},
                    CondNotifyCcRole: {},
                  },
                },
              },
            },
            CheckList: {},
            Conditions: {},
          },
        },
        Conditions: {},
      },
      stagemid: {
        Name: 'stageMID',
        FriendlyName: 'stage in mid',
        Guid: 'stagemid',
        Status: '1',
        WorkFlowId: 'bgE6hpSnpBZTu@tVOEGgDA==',
        WfoId: 'kpt7QKoHOTqCPyiH9HKuGg==',
        States: {
          stateinstg3: {
            Name: 'stateinstg3',
            FriendlyName: 'state in stage 3',
            Status: '1',
            Guid: 'stateinstg3',
            SpecID: '0',
            SpecificationName: '',
            WfosId: '0DvcHM$$$ljcBwgCjXTXpbIg==',
            WfoId: 'kpt7QKoHOTqCPyiH9HKuGg==',
            StateType: '',
            StateRoles: {},
            Triggers: {},
            CheckList: {},
            Conditions: {},
          },
        },
        Conditions: {},
      },
    },
    BusinessModels: {},
    WorkflowRoles: {},
  },
  Coordinates: {
    Collaboration_0o8k858: {
      height: 80,
      width: 100,
      name: '',
    },
    WFApp1: {
      height: 760,
      width: 400,
      x: 350,
      y: -800,
      name: 'WFApp1',
    },
    stg1app1: {
      height: 410,
      width: 370,
      x: 380,
      y: -800,
      name: 'Stg1_app1',
    },
    St2app1: {
      height: 36,
      width: 36,
      x: 592,
      y: -778,
      name: 'St2_app1',
    },
    Event_1391qrr_label: {
      height: 14,
      width: 48,
      x: 586,
      y: -802,
      name: 'St2_app1',
    },
    St3app1: {
      height: 36,
      width: 36,
      x: 492,
      y: -638,
      name: 'St3_app1',
    },
    Event_1jot794_label: {
      height: 14,
      width: 48,
      x: 486,
      y: -662,
      name: 'St3_app1',
    },
    stagemid: {
      height: 210,
      width: 370,
      x: 380,
      y: -390,
      name: 'stage in mid',
    },
    stateinstg3: {
      height: 36,
      width: 36,
      x: 512,
      y: -258,
      name: 'state in stage 3',
    },
    Event_0qudqmy_label: {
      height: 14,
      width: 75,
      x: 493,
      y: -215,
      name: 'state in stage 3',
    },
    stg2app1: {
      height: 140,
      width: 370,
      x: 380,
      y: -180,
      name: 'Stg2_app1',
    },
    St4app1: {
      height: 36,
      width: 36,
      x: 442,
      y: -118,
      name: 'St4_app1',
    },
    Event_01nxxdl_label: {
      height: 14,
      width: 48,
      x: 436,
      y: -75,
      name: 'St4_app1',
    },
    trg2app1: {
      height: 80,
      width: 100,
      name: 'Trg2_app1',
      waypoints: [
        {
          x: 610,
          y: -742,
          original: {
            x: 610,
            y: -760,
          },
        },
        {
          x: 610,
          y: -620,
        },
        {
          x: 528,
          y: -620,
          original: {
            x: 510,
            y: -620,
          },
        },
      ],
    },
    trg2app1_label: {
      height: 14,
      width: 53,
      x: 512,
      y: -622,
      name: 'Trg2_app1',
    },
    trg3app1: {
      height: 80,
      width: 100,
      name: 'Trg3_app1',
      waypoints: [
        {
          x: 492,
          y: -620,
          original: {
            x: 510,
            y: -620,
          },
        },
        {
          x: 460,
          y: -620,
        },
        {
          x: 460,
          y: -118,
          original: {
            x: 460,
            y: -100,
          },
        },
      ],
    },
    trg3app1_label: {
      height: 14,
      width: 53,
      x: 449,
      y: -133,
      name: 'Trg3_app1',
    },
    'bpmn:ExclusiveGateway*firsttomid': {
      height: 50,
      width: 50,
      x: 505,
      y: -365,
      name: '',
    },
    firsttomid: {
      height: 80,
      width: 100,
      name: 'test mid ex',
      waypoints: [
        {
          x: 510,
          y: -602,
          original: {
            x: 510,
            y: -620,
          },
        },
        {
          x: 510,
          y: -543,
        },
        {
          x: 530,
          y: -543,
        },
        {
          x: 530,
          y: -365,
          original: {
            x: 530,
            y: -340,
          },
        },
      ],
    },
    firsttomid_label: {
      height: 14,
      width: 54,
      x: 488,
      y: -576,
      name: 'test mid ex',
    },
    testStar: {
      height: 36,
      width: 36,
      x: 442,
      y: -758,
      name: 'test start state',
    },
  },
};
